### PR TITLE
Add support for Wokwi CLI log serial option

### PR DESCRIPTION
**Pull request by PBrunot**
As per [CLI Options](https://docs.wokwi.com/wokwi-ci/getting-started)

### CODE REVIEW

**Comment by urish** [comment]
Thanks! Have you tested what happens if `serial_log_file` is not specified?

**Comment by PBrunot** [comment]
No. I'm not really familiar with Github action development. Do you know how
I could test with my fork?

Il giorno sab 6 gen 2024 alle ore 12:45 Uri Shaked ***@***.***>
ha scritto:

**Comment by urish** [comment]
Yeah, just point the action at `PBrunot/wokwi-ci-action@add_log_serial`

**Comment by PBrunot** [comment]
I've tested with and without serial_log_file arguments, fixed a bug, and it works properly now.
Example run here : https://github.com/PBrunot/rfid-arduino-copy/actions/runs/7431731024 (I'm able to capture artifacts now)

I've noticed the $GITHUB_WORKSPACE does not get expanded, it is unrelated but you may want to look at this:
image

**Comment by urish** [comment]
Thank you!

**Pull request merged**
